INSERT INTO orgao_expeditor(sigla, nome) VALUES ('SSP','Secretaria de Segurança Públicaa');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('PM', 'Polícia Militar'); 
INSERT INTO orgao_expeditor(sigla, nome) VALUES('PC', 'Policia Civil'); 
INSERT INTO orgao_expeditor(sigla, nome) VALUES('CNT', 'Carteira Nacional de Habilitação'); 
INSERT INTO orgao_expeditor(sigla, nome) VALUES('DIC', 'Diretoria de Identificação Civil'); 
INSERT INTO orgao_expeditor(sigla, nome) VALUES('CTPS', 'Carteira de Trabaho e Previdência Social');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('FGTS', 'Fundo de Garantia do Tempo de Serviço'); 
INSERT INTO orgao_expeditor(sigla, nome) VALUES('IFP', 'Instituto Félix Pacheco');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('IPF', 'Instituto Pereira Faustino');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('IML', 'Instituto Médico-Legal');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('MTE', 'Ministério do Trabalho e Emprego');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('MMA', 'Ministério da Marinha');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('MAE', 'Ministério da Aeronáutica');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('MEX', 'Ministério do Exército'); 
INSERT INTO orgao_expeditor(sigla, nome) VALUES('POF', 'Polícia Federal');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('POM', 'Polícia Militar'); 
INSERT INTO orgao_expeditor(sigla, nome) VALUES('SES', 'Carteira de Estrangeiro');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('SJS', 'Secretaria da Justiça e Segurança');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('SJTS', 'Secretaria da Justiça do Trabalho e Segurança');
INSERT INTO orgao_expeditor(sigla, nome) VALUES('ZZZ', 'Outros (inclusive exterior));